name: Feature Request
description: Suggest a new hook, utility, or improvement to the project
labels: ['🚀 Enhancement']
body:
  - type: textarea
    attributes:
      label: Problem Description
      description: Please provide a clear and concise description of the problem or limitation you've encountered.
      placeholder: |
        I often find myself needing a specific functionality when working with React components, but the current set of hooks and utilities doesn't cover this use case.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the new hook, utility, or improvement you'd like to see added to the project.
      placeholder: |
        Add a new hook called `useXYZ` that provides the following functionality:
        - Ability to do X
        - Integration with Y
        - Support for Z
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds? Please describe them here.
      placeholder: |
        I've tried using a combination of existing hooks like `useABC` and `useDEF`, but it doesn't quite achieve the desired behavior.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Category
      description: Select the category that best fits your feature request.
      options:
        - 'New Hook'
        - 'New Utility Function'
        - 'Enhancement to Existing Hook/Utility'
        - 'Documentation Improvement'
        - 'Other'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: Provide a specific use case or example scenario where this new feature would be beneficial.
      placeholder: |
        This new hook would be particularly useful when building complex forms with dynamic fields and validation requirements.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references that support your feature request.
    validations:
      required: false
